=== ElGoorf/gogen-solver/packages/samples/schema/sample.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "Gogen Schema",
  "required": [
    "grid",
    "words"
  ],
  "properties": {
    "description": {
      "type": "string",
      "title": "Description Schema",
      "description": "Eg. source of the sample",
      "examples": ["London Evening Standard: Jan 26th 2018"]
    },
    "grid": {
      "type": "array",
      "title": "Grid Schema",
      "description": "2D Array of letters.",
      "items": {
        "type": "array",
        "items": {
          "type": "string",
          "default": "_",
          "pattern": "^[a-zA-Z_]$"
        }
      }
    },
    "words": {
      "type": "array",
      "title": "Words Schema",
      "description": "List of words given for the puzzle.",
      "items": {
        "type": "string",
        "default": "",
        "pattern": "^([a-zA-Z]*)$"
      }
    },
    "solution": {
      "$ref": "#/properties/grid",
      "description": "The grid, but solved."
    }
  }
}

=== ElGoorf/gogen-solver/packages/samples/src/samples/ES_2018-01-26.json
{
  "description": "London Evening Standard: Jan 26th 2018",
  "grid": [
    ["Y", "_", "W", "_", "H"],
    ["_", "_", "_", "_", "_"],
    ["Q", "_", "X", "_", "D"],
    ["_", "_", "_", "_", "_"],
    ["T", "_", "G", "_", "C"]
  ],
  "words": [
    "BUG",
    "CLING",
    "DAMPING",
    "FOIL",
    "FOX",
    "HARM",
    "HAVOC",
    "JAM",
    "KEY",
    "PEW",
    "SQUINT",
    "YEW"
  ],
  "solution": [
    ["Y", "K", "W", "R", "H"],
    ["S", "E", "M", "A", "J"],
    ["Q", "P", "X", "V", "D"],
    ["B", "U", "I", "O", "F"],
    ["T", "N", "G", "L", "C"]
  ]
}
